# Generated by Django 2.1.2 on 2019-09-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicletype',
            name='entry_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='exit_time',
            field=models.DateTimeField(null=True),
        ),
    ]
